// screens/ThreadSummaryScreen.js
import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import ScreenLayout from '../components/ScreenLayout';
import { useSettings } from '../contexts/SettingsContext';

export default function ThreadSummaryScreen({ route, navigation }) {
  const { postTitle, summary } = route.params;
  const { themeColors, accentPreset } = useSettings();

  return (
    <ScreenLayout
      title="Thread Summary"
      subtitle="AI-generated summary"
      navigation={navigation}
      onBack={() => navigation.goBack()}
      showFooter={false}
    >
      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={true}
      >
        {/* Post Title Section */}
        <View style={[styles.titleSection, { backgroundColor: themeColors.card }]}>
          <View style={styles.titleHeader}>
            <Ionicons
              name="document-text"
              size={20}
              color={accentPreset?.buttonBackground || themeColors.primary}
            />
            <Text style={[styles.titleLabel, { color: themeColors.textSecondary }]}>
              Post Title
            </Text>
          </View>
          <Text style={[styles.postTitle, { color: themeColors.textPrimary }]}>
            {postTitle}
          </Text>
        </View>

        {/* Summary Section */}
        <View style={[styles.summarySection, { backgroundColor: themeColors.card }]}>
          <View style={styles.summaryHeader}>
            <Ionicons
              name="bulb"
              size={20}
              color={accentPreset?.buttonBackground || themeColors.primary}
            />
            <Text style={[styles.summaryLabel, { color: themeColors.textSecondary }]}>
              Summary
            </Text>
          </View>
          <Text style={[styles.summaryText, { color: themeColors.textPrimary }]}>
            {summary}
          </Text>
        </View>

        {/* Info Footer */}
        <View style={styles.infoFooter}>
          <Ionicons name="information-circle-outline" size={16} color={themeColors.textSecondary} />
          <Text style={[styles.infoText, { color: themeColors.textSecondary }]}>
            This summary was generated by AI and may not capture all nuances of the discussion.
          </Text>
        </View>
      </ScrollView>
    </ScreenLayout>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  titleSection: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
  },
  titleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  titleLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  postTitle: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
  },
  summarySection: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryText: {
    fontSize: 15,
    lineHeight: 24,
  },
  infoFooter: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingHorizontal: 4,
  },
  infoText: {
    fontSize: 12,
    lineHeight: 18,
    flex: 1,
  },
});
